import '../index.css'

export const metadata = {
  title: 'upsquad',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-text-primary">
        {children}
      </body>
    </html>
  )
}
