import '../index.css'

export const metadata = {
  title: 'upsquad',
  description: 'Generated by create next app',
  icons: { icon: '/favicon.svg' }
}

// Applies the saved theme before first paint to avoid a flash.
// Default is ALWAYS light — OS `prefers-color-scheme` is intentionally
// ignored, so the site loads light even when the system is in dark mode.
const themeInit = `(function(){try{if(localStorage.getItem('upsquad-theme')==='dark'){document.documentElement.classList.add('dark')}}catch(e){}})();`

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
      </head>
      <body className="min-h-screen text-text-primary">
        {children}
      </body>
    </html>
  )
}
